# Generated by Django 3.2.4 on 2021-07-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=6, verbose_name='产品名称')),
                ('product_detail', models.CharField(max_length=500, verbose_name='产品详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price', models.FloatField(verbose_name='价格')),
                ('inventory', models.IntegerField(verbose_name='库存')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.producttype', verbose_name='产品类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth_user.yonghu', verbose_name='发表用户')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
    ]
