# Generated by Django 3.2.4 on 2021-07-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_yonghu_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonghu',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='是否已认证'),
        ),
    ]
