# Generated by Django 3.2.4 on 2021-07-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_yonghu_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发送时间'),
        ),
    ]
