# Generated by Django 3.2.4 on 2021-06-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensitives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitive_words', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('introduction', models.CharField(blank=True, max_length=100, null=True)),
                ('verification', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification_Code',
            fields=[
                ('verificationId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('verification_type', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.user')),
            ],
        ),
    ]
