# Generated by Django 3.2.4 on 2021-06-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification_code',
            name='update_time',
        ),
    ]
