# Generated by Django 3.2.4 on 2021-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_verification_code_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification_code',
            name='userid',
        ),
        migrations.AddField(
            model_name='verification_code',
            name='phoneOrEmail',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
