# Generated by Django 3.2.4 on 2021-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('url', models.CharField(max_length=256, verbose_name='访问地址')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='访问日期')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
            },
        ),
    ]
