# Generated by Django 3.2.4 on 2021-06-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0005_alter_verification_code_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('url', models.CharField(max_length=256, verbose_name='访问地址')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='访问日期')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth_user.user')),
            ],
        ),
    ]
