# Generated by Django 3.2.4 on 2021-07-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_log', '0001_initial'),
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth_user.yonghu'),
        ),
    ]
