# Generated by Django 3.2.4 on 2021-06-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'verbose_name': '访问日志', 'verbose_name_plural': '访问日志'},
        ),
    ]
