# Generated by Django 3.2.4 on 2021-07-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensitives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitive_words', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('verificationId', models.AutoField(primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('phone', '手机号'), ('email', '邮箱')], max_length=10, verbose_name='验证类型')),
                ('phoneOrEmail', models.CharField(max_length=100, verbose_name='邮箱或手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.CreateModel(
            name='Yonghu',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('introduction', models.CharField(blank=True, max_length=100, null=True, verbose_name='个人介绍')),
                ('verification', models.BooleanField(verbose_name='是否已认证')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='image.imagepath', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
