# Generated by Django 3.2.4 on 2021-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product_name',
            field=models.CharField(max_length=20, verbose_name='产品名称'),
        ),
    ]
