# Generated by Django 3.2.4 on 2021-06-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='inventory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
